/*
THIS TEST EXISTS PURELY TO FIX A RANDOM ISSUE WITH PIO TESTING WHICH CAUSES THE FIRST TEST TO FAIL DUE TO PACKAGE WHATNOT
DO NOT ACTUALLY POPULATE THIS TEST AND ENSURE IT RUNS FIRST TO ESTABLISH THE TESTING ENVIRONMENT
IF IT FAILS, IGNORE
*/

#include <unity.h>
#include <Arduino.h>

void setUp(void) {}
void tearDown(void) {}

int main(int argc, char **argv) {
    UNITY_BEGIN();
    UNITY_END();
}